services:
  qingping-co2-temp-rh-sensor-parser:
    restart: always
    build: .
    environment:
      - MQTT_SERVER=10.0.0.200
      - MQTT_PORT=1883
      - SENSOR_TOPIC=qingping/582D3481AC41/up
      - SENSOR_MAC=582D3481AC41
